### ISSUE TITLE
Called Delete on an entity already being deleted. Entity: туловище животного

### ISSUE THREAD

**Issue by KIBORG04** [space-syndicate/space-station-14#945]
### Описание

Тест рандомно валится, высвечивая некрасивый красный крестик, когда мог бы не высвечивать

https://github.com/space-syndicate/space-station-14/actions/runs/4576740736/jobs/8081267715
https://github.com/space-syndicate/space-station-14/actions/runs/4576313393/jobs/8080280115
https://github.com/space-syndicate/space-station-14/actions/runs/4566594002/jobs/8059314606

```cs
A total of 1 test files matched the specified pattern.
  Failed Test [1 s]
  Error Message:
   System.InvalidOperationException : Called Delete on an entity already being deleted. Entity: задние лапы животного (179571, LegsAnimal)
  Stack Trace:
     at Robust.Shared.GameObjects.EntityManager.DeleteEntity(EntityUid e) in D:\a\space-station-[14](https://github.com/space-syndicate/space-station-14/actions/runs/4576740736/jobs/8081267715#step:10:15)\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 309
   at Robust.Shared.GameObjects.EntityManager.FlushEntities() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 500
   at Robust.Shared.GameObjects.EntityManager.Cleanup() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 1[21](https://github.com/space-syndicate/space-station-14/actions/runs/4576740736/jobs/8081267715#step:10:22)
   at Robust.Server.BaseServer.Cleanup() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 634
   at Robust.Server.BaseServer.FinishMainLoop() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 529
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in D:\a\space-station-14\space-station-14\RobustToolbox\Robust.UnitTesting\RobustIntegrationTest.cs:line 584
   ```

### Шаги воспроизведения

1. Перезапускать экшносы на сбилдивание до тех пор, пока тест не умрёт на очередном туловище животного
![image](https://user-images.githubusercontent.com/26389417/229323475-cacfbaf6-53be-4785-be52-592a14f6227b.png)

### Скриншоты

![image](https://user-images.githubusercontent.com/26389417/229323504-30185dcf-09f7-4dc6-941d-7b5b554975ef.png)
![image](https://user-images.githubusercontent.com/26389417/229323543-b38d9f80-966a-49b5-8a0b-f81ec00e4df3.png)
![image](https://user-images.githubusercontent.com/26389417/229323553-7bf68ab5-e4fb-4f61-bdc0-9990b1307983.png)

**Comment by Morb0** [comment]
Проблема не только нашего форка
https://github.com/StationWare/stationware/actions/runs/4528709249/jobs/7975739169
https://github.com/Nyanotrasen/Nyanotrasen/actions/runs/4602294532/jobs/8131097816
Если бы только это можно было локально воспроизвести

**Comment by KIBORG04** [comment]
Странно, но ведь тогда должна быть такая же проблема и на апстриме, но на апстриме я ничего похожего не нашёл.

**Comment by Morb0** [comment]
Moved to https://github.com/space-wizards/space-station-14/issues/15142
